-- ALTER SESSION SET CURRENT_SCHEMA = CBRENNAN; SET IT TO HIS SCHEMA
 
UPDATE CD_ATTENDEE SET Coder_Name = 'Hi Hello' WHERE Coder_ID = '5000';
COMMIT;

ALTER SESSION SET CURRENT_SCHEMA = SBARLAS;

CREATE TABLE Academic
(
  key int,
  Name varchar(255) NOT NULL
);
  
GRANT SELECT ON ACADEMIC TO CBRENNAN; -- GIVING ACCES TO CBRENNAN
GRANT UPDATE ON ACADEMIC TO CBRENNAN; -- ALLOWS UPDATES
GRANT INSERT ON ACADEMIC TO CBRENNAN; -- INSERT DATA
  
CREATE SEQUENCE ACAD_SEQ START WITH 100000 INCREMENT BY 1;
  
--grant usage on sequence ACAD_SEQ to CBRENNAN;
GRANT SELECT on acad_seq to cbrennan;
  
SELECT * FROM ACADEMIC;
